/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author angie
 */
public class VistaPregunta extends javax.swing.JFrame {

    /**
     * Creates new form VistaPregunta
     */
    public VistaPregunta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pregunta_txt = new javax.swing.JLabel();
        no_btn = new javax.swing.JButton();
        si_btn = new javax.swing.JButton();
        reiniciar_btn = new javax.swing.JButton();
        salir_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El Mundo de los Animales");

        pregunta_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pregunta_txt.setText("Pregunta");

        no_btn.setText("No");
        no_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_btnActionPerformed(evt);
            }
        });

        si_btn.setText("Sí");
        si_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si_btnActionPerformed(evt);
            }
        });

        reiniciar_btn.setText("Reiniciar");

        salir_btn.setText("Salir");
        salir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pregunta_txt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salir_btn)
                            .addComponent(reiniciar_btn))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(no_btn)
                        .addGap(48, 48, 48)
                        .addComponent(si_btn)
                        .addContainerGap(246, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(reiniciar_btn)
                        .addGap(26, 26, 26)
                        .addComponent(salir_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pregunta_txt)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_btn)
                    .addComponent(si_btn))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_btnActionPerformed

    private void si_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_si_btnActionPerformed

    private void salir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salir_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton no_btn;
    private javax.swing.JLabel pregunta_txt;
    private javax.swing.JButton reiniciar_btn;
    private javax.swing.JButton salir_btn;
    private javax.swing.JButton si_btn;
    // End of variables declaration//GEN-END:variables

    public void notify(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    //gets
    public String getPregunta_txt(){
        return this.pregunta_txt.getText();
    }
    
    public String getNoBtn_txt(){
        return this.no_btn.getText();
    }
    
    public String getSiBtn_txt(){
        return this.si_btn.getText();
    }
    
    public JFrame getVentanaPregunta(){
        return this;
    }
    // sets
    
    public void setPregunta_txt(String text){
        this.pregunta_txt.setText(text);
    }
    
    // add

    public void addNo_btn(ActionListener listener){
        this.no_btn.addActionListener(listener);
    }
    
    public void addSi_btn(ActionListener listener){
        this.si_btn.addActionListener(listener);
    }
    
    public void addReiniciar_btn(ActionListener listener){
        this.reiniciar_btn.addActionListener(listener);
    }
    
    public void addSalir_btn(ActionListener listener){
        this.salir_btn.addActionListener(listener);
    }
    
}
